[env:esp32cam-usb]
platform = espressif32
board = esp32cam
framework = arduino
upload_speed = 921600
monitor_speed = 115200
board_build.psram = enabled
lib_deps = espressif/esp32-camera@^2.0.4
board_build.partitions = partitions.csv

[env:esp32cam-ota]
platform = espressif32
board = esp32cam
framework = arduino
upload_protocol = espota
upload_port = 192.168.1.17   
monitor_speed = 115200
board_build.psram = enabled
lib_deps = espressif/esp32-camera@^2.0.4
board_build.partitions = partitions.csv
